### ISSUE TITLE
add carmen-rails to rubygems

### ISSUE THREAD

**Issue by joeytheman** [carmen-ruby/carmen-rails#1]
carmen-rails will only install with bundler when the git location of both `carmen` and `carmen-rails` `1.0.0.pre`  is specified my gem file.

**Comment by jim** [comment]
I'm in the process of converting the locale files from the old format to the new one the carmen gem. Once that is complete, I'll release beta 1 of both projects.

**Comment by jim** [comment]
I just pushed carmen-rails 1.0.0.beta1 to Rubygems.
