### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by andriytyurnikov** [carmen-ruby/carmen-rails#4]
/Users/andriytyurnikov/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/carmen-rails-958b23d8e0d5/lib/carmen-rails.rb:8:in `<class:Railtie>': undefined method`i18n_backend' for Carmen:Module (NoMethodError)

gem needs initializer or something?

**Comment by jim** [comment]
There was a missing require in 1.0.0.beta1 that I didn't catch because of the setup of my test app. This is fixed in 1.0.0.beta2.
