### ISSUE TITLE
Please release new gem version

### ISSUE THREAD

**Issue by tmaier** [carmen-ruby/carmen-rails#42]
Hi there,

There are a lot of useful changes in carmen-rails.
https://github.com/jim/carmen-rails/compare/v1.0.0...master

Could you please release a new version of the gem.

Thank you

**Comment by basti** [comment]
:+1:

**Comment by wesvetter** [comment]
+1

**Comment by ckhall** [comment]
yes, i'm currently having to point to master to get around a bug.

**Comment by jim** [comment]
Sorry for the delay. I'm a bit behind on PRs, but I will get a new version out before too long.

**Comment by tmaier** [comment]
@jim Thank you for releasing [v1.0.1](http://rubygems.org/gems/carmen-rails/versions/1.0.1)
