### ISSUE TITLE
how to give prompt when showing only 2 countries using only_us_and_canada method.

### ISSUE THREAD

**Issue by dinshawraje** [carmen-ruby/carmen-rails#54]
when I am writing this `<%= f.select :country, region_options_for_select(only_us_and_canada) %>`
 I want to show first option to be select country and then the names of country i.e want to give prompt. Please help me out in this.

**Comment by jim** [comment]
Take a look at the [Rails docs for select](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html). Something like this should work:

``` erb
<%= f.select :country, region_options_for_select(only_us_and_canada), {prompt: 'Select Country'} %>
```
