### ISSUE TITLE
I'd like to be the maintainer (too)

### ISSUE THREAD

**Issue by jtapia** [carmen-ruby/carmen-rails#55]

**Comment by jim** [comment]
Hey there! Thanks for volunteering. I've added you to this repo and to [carmen](http://github.com/jim/carmen).

Our most urgent needs are PR triaging and updates for Rails 4. Ping @CDainMiller, @ecbypi, or me if you have any questions and we'll try to help.

**Comment by ghost** [comment]
Hey J! Glad to have ya. :) 

I agree with Jim, would be great to get some Rails 4 love. 

Let us know if you have any Questions!

**Comment by jtapia** [comment]
Hey guys, 

Thanks for the add, I’ll try to contribute to this great project, and sure, I’ll start to work to implement the support for Rails 4. Let me know if have any other plan.

Greetings!

**Comment by jtapia** [comment]
Hi guys, 

I want to ask you what is the development process I should follow, I mean, branch off from "master" and later create a PR to master or create a “develop” branch and the PRs to it and later to “master"? sorry to bother you guys, I’m doing some quick fixes to support Rails > 4.0

Thanks

**Comment by jim** [comment]
We haven't had a very formal process so far, but we typically do
development with PRs to master. In the past I have used longer-lived
development branches for big changes, but for most work it is probably
overkill.

Thanks for helping out, and feel free to ask any other questions!

## 

Jim Benton
312-730-7550

**Comment by jtapia** [comment]
Hi,

Working with Rails 4.2, I noticed that we need to do some changes to support it, some methods changed, etc. I was woking fixing the test build and for Rails 4.2 we need Nokogiri, etc., my question is, should we consider to create a rails4 branch? or should I try to find a way to make them fixed on master branch?

Thanks!

**Comment by ecbypi** [comment]
@jtapia, I started a branch to get tests working across different versions of rails: rails-testing. There are some issues with the Appraisal gemfiles on some builds (no clue why) and failures from removing byebug and debugger from the gemspec but not test_helper.rb. 

Feel free to take a look.

**Comment by jtapia** [comment]
Hi guys, 

I sent a PR to add support for Rails 4.2, basically I started using Eduardo Gutierrez branch(rails-testing) and fix some things to run tests and everything is working well, I think it’s in good shape to be merged, could you take a look and tell me what do you think?

Thanks!
