### ISSUE TITLE
subregion_select should support setting a prompt

### ISSUE THREAD

**Issue by jim** [carmen-ruby/carmen-rails#8]
[See also](https://github.com/jim/carmen/issues/94).

**Comment by rdsoze** [comment]
An include_blank works with subregion_select .. 
Edit: prompt also works :P

``` ruby
 <%= f.subregion_select(:state, 'US', :prompt => "Select if applicable" ) %>
```

If you had anything else in mind, I would definitely take a stub at it ..

**Comment by peng-zuo** [comment]
i think jim meant subregion_select_tag and country_select_tag, the html_options is not included in these methods.
